package package1;

import java.io.FileOutputStream;
import java.io.FileReader;
import java.sql.Connection;
import java.util.Properties;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gaurav
 */
public class Launch extends javax.swing.JFrame {

    /**
     * Creates new form DatabaseReset
     */
        static Connection connection=null;
    
         String ip;
         String port;
         String user;
         String pswd;
         String dbName;
         String dbSchemaName;
                 
    public Launch() {
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlaple360 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newip = new javax.swing.JTextField();
        newport = new javax.swing.JTextField();
        newdbuser = new javax.swing.JTextField();
        newdbpswd = new javax.swing.JTextField();
        connectdb = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dbselect = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        newSchemaName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SPENDING TRACKER");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(200, 227, 139));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2754575-128.png"))); // NOI18N
        jLabel1.setText("Database Admin");

        jButton1.setBackground(new java.awt.Color(233, 70, 91));
        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setText("Restart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(246, 246, 194));

        jlaple360.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jlaple360.setText("   ip:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("port:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("user:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("password:");

        newip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newipActionPerformed(evt);
            }
        });

        newport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newportActionPerformed(evt);
            }
        });

        newdbuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newdbuserActionPerformed(evt);
            }
        });

        newdbpswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newdbpswdActionPerformed(evt);
            }
        });

        connectdb.setBackground(new java.awt.Color(203, 18, 76));
        connectdb.setText("CONNECT");
        connectdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectdbActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/379393-64.png"))); // NOI18N
        jLabel5.setText("Database Configurations");

        dbselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mysql", "postgres", "oracle" }));
        dbselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbselectActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("DB Name:");

        newSchemaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSchemaNameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Schema name :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jlaple360, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newSchemaName)
                    .addComponent(dbselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newport)
                    .addComponent(newdbuser)
                    .addComponent(newdbpswd, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(newip))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(connectdb, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlaple360))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newdbuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newdbpswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSchemaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(connectdb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(252, 250, 212));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/erd (1).png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(26, 16, 16));
        jLabel9.setText("-Please make sure you are connected to internet if you are using default Database.");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(7, 2, 2));
        jLabel10.setText("-OR if you want to use your own database  use below diagram to create your own table.");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(35, 28, 28));
        jLabel11.setText("-if you are not sure what to do contact me on [gs89035@gmail.com]");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(37, 18, 18));
        jLabel12.setText("-OR just import the file in your database given in DB folder of project.");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/465064-64.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newipActionPerformed

    private void newportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newportActionPerformed

    private void newdbuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newdbuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newdbuserActionPerformed

    private void newdbpswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newdbpswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newdbpswdActionPerformed

    private void connectdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectdbActionPerformed
        //Reset Db values 
         this.dbName=dbselect.getSelectedItem().toString();
         this.ip=newip.getText();
         this.port=newport.getText();
         this.user=newdbuser.getText();
         this.pswd=newdbpswd.getText();
         this.dbSchemaName=newSchemaName.getText();
                  
         //LoginFrame lf=new LoginFrame(ip,port,user,pswd);
               
                //JOptionPane.showMessageDialog(this,"Paramiters=="+ip+port+user+pswd+dbName+dbSchemaName);
                connection=new DbConnect(ip,port,user,pswd,dbName,dbSchemaName).connectDb();
                if(connection!=null)
                {
                   JOptionPane.showMessageDialog(this,"Connection Succesful");
                   try
                   {
                       //for reading of linux in runtime
                  FileReader reader=new FileReader("lib/db.properties");  
                  
                  Properties p=new Properties();  
                  p.load(reader);
                  p.setProperty("dbname", dbName);
                  p.setProperty("ip", ip);
                  p.setProperty("port", port);
                  p.setProperty("user", user);
                  p.setProperty("password", pswd);
                  p.setProperty("dbschema", dbSchemaName);
                  p.store(new FileOutputStream("lib/db.properties"), null);
                   }catch(java.io.FileNotFoundException ioe)
                   {
                       
                       try
                       {
                           //for reading of windows in runtime
                          FileReader reader1=new FileReader("C:\\Program Files\\SpendingTracker\\lib\\db.properties");
                           Properties p=new Properties();  
                             p.load(reader1);
                            p.setProperty("dbname", dbName);
                            p.setProperty("ip", ip);
                            p.setProperty("port", port);
                            p.setProperty("user", user);
                            p.setProperty("password", pswd);
                            p.setProperty("dbschema", dbSchemaName);
                            p.store(new FileOutputStream("C:\\Program Files\\SpendingTracker\\lib\\db.properties"), null);
                          
                       }
                       
                        catch(java.io.FileNotFoundException e1)
                         {
                            JOptionPane.showMessageDialog(this,e1);
                         }
                       catch(Exception e2)
                       {
                           
                       }
                   }
                   catch(Exception e)
                    {
                        
                         JOptionPane.showMessageDialog(this,e);
                    }
                   

                   dispose();        
                   LoginFrame lf1= new LoginFrame(connection);
                   lf1.setVisible(true);
            
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Not connected");
                    
                }
         
        // lf.dispose();
         
         
    }//GEN-LAST:event_connectdbActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void dbselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbselectActionPerformed

    private void newSchemaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSchemaNameActionPerformed
        // TODO add your handling code here:
        //Reset Db values 
      this.dbName=dbselect.getSelectedItem().toString();
         this.ip=newip.getText();
         this.port=newport.getText();
         this.user=newdbuser.getText();
         this.pswd=newdbpswd.getText();
         this.dbSchemaName=newSchemaName.getText();
        
         
         //LoginFrame lf=new LoginFrame(ip,port,user,pswd);
               
           //     JOptionPane.showMessageDialog(this,"Paramiters=="+ip+port+user+pswd+dbName+dbSchemaName);
                connection=new DbConnect(ip,port,user,pswd,dbName,dbSchemaName).connectDb();
                if(connection!=null)
                {
                   JOptionPane.showMessageDialog(this,"Connection Succesful");
                    try
                    {
                     FileReader reader=new FileReader("lib/db.properties");  
                     Properties p=new Properties();  
                     p.load(reader);
                     p.setProperty("dbname", dbName);
                     p.setProperty("ip", ip);
                     p.setProperty("port", port);
                     p.setProperty("user", user);
                     p.setProperty("password", pswd);
                     p.setProperty("dbschema", dbSchemaName);
                     p.store(new FileOutputStream("lib/db.properties"), null);
                     }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this,e);
                    }
                   dispose();        
                   LoginFrame lf1= new LoginFrame(connection);
                   lf1.setVisible(true);
            
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Not connected");
                    
                }
         
    }//GEN-LAST:event_newSchemaNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:catch
             dispose();
             try
             {
                   FileReader reader=new FileReader("lib/db.properties");  
                 Properties p=new Properties();  
                  p.load(reader);  
                  
                    
             String ip1=p.getProperty("ip");
             String port1=p.getProperty("port");
             String user1=p.getProperty("user");
             String pswd1=p.getProperty("password");
             String dbName1=p.getProperty("dbname");
             String dbSchemaName1=p.getProperty("dbschema");
             
              connection=new DbConnect(ip1,port1,user1,pswd1,dbName1,dbSchemaName1).connectDb();
             if(connection!=null)
             {
                 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new LoginFrame(connection).setVisible(true);
                
               }
               });
                 
             }
             else
             {
                 java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                    new Launch().setVisible(true);
                  }
                 });
                 
             }
             }catch(Exception e)
             {
                 JOptionPane.showMessageDialog(this,e);
             }
              
             
            
//             
//              String ip="sql12.freemysqlhosting.net";
//             String port="3306";
//             String user="sql12392471";
//             String pswd="59JSdZAp2H";
//             String dbName="mysql";
//             String dbSchemaName="sql12392471";
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
             /* Create and display the form */
            
                  FileReader reader=new FileReader("lib/db.properties");  
                 Properties p=new Properties();  
                  p.load(reader);  
                  
                    
             String ip=p.getProperty("ip");
             String port=p.getProperty("port");
             String user=p.getProperty("user");
             String pswd=p.getProperty("password");
             String dbName=p.getProperty("dbname");
             String dbSchemaName=p.getProperty("dbschema");
             
            
//             
//              String ip="sql12.freemysqlhosting.net";
//             String port="3306";
//             String user="sql12392471";
//             String pswd="59JSdZAp2H";
//             String dbName="mysql";
//             String dbSchemaName="sql12392471";
             connection=new DbConnect(ip,port,user,pswd,dbName,dbSchemaName).connectDb();
             if(connection!=null)
             {
                 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new LoginFrame(connection).setVisible(true);
                
               }
               });
                 
             }
             else
             {
                 java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                    new Launch().setVisible(true);
                  }
                 });
                 
             }
            
                     
                
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectdb;
    private javax.swing.JComboBox<String> dbselect;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlaple360;
    private javax.swing.JTextField newSchemaName;
    private javax.swing.JTextField newdbpswd;
    private javax.swing.JTextField newdbuser;
    private javax.swing.JTextField newip;
    private javax.swing.JTextField newport;
    // End of variables declaration//GEN-END:variables
}
